#!/usr/bin/env python

import argparse

import settings

from lib.rag_loader import RAGLoader
from lib.rag_query import RAGQuery
from lib.utils import *

parser = argparse.ArgumentParser()
parser.add_argument("--list", action="store_true", help="List the files in the RAG")
parser.add_argument("--add_file", type=str, help="Add a document to the database")
parser.add_argument("--add_dir", type=str, help="Add a directory of files to the database")
parser.add_argument("--query", type=str, help="Ask a question via the RAG")
parser.add_argument("--reset", action="store_true", help="Reset the database")
parser.add_argument("--delete", type=str, help="The file to remove")
parser.add_argument("--debug", action="store_true", help="Debug stuff")
args = parser.parse_args()

loader = RAGLoader(args.debug)

if args.list:
    list_files(loader.collection)
elif args.delete:
    delete_file(loader.collection, args.delete)
elif args.query:
    rq = RAGQuery(loader.collection)
    rq.query(args.query, args.debug)
elif args.reset:
    loader.reset()
elif args.add_file:
    loader.load_file(args.add_file)
elif args.add_dir:
    loader.load_directory(args.add_dir)
else:
    parser.print_help()
